### ISSUE TITLE
[SUGGESTION] AME Playbook

### ISSUE THREAD

**Issue by MarcoRavich** [mewostick/WinScripts#1]
Hi there, dunno if this is related somehow to your other repo (SamuraiOS), anyway sounds interesting.

As many [Windows-customs](https://github.com/MarcoRavich/Opendows#open-source-customized-windows-isos) have already done, I strongly suggest to release an [Playbook](https://docs.ameliorated.io/playbooks.html) version trough [AME Wizard](https://ameliorated.io/) too.

Last but not least, consider that many people uses (or are forced to use) Windows for multimedia productions, but obtaining an optimized configuration is not for everyone.

It would be extremely useful (to push your work adoption/diffusion too) to have a dedicated/customized Windows for this purpose.

Some interesting resources about by audio manufacturers:
- PreSonus' [Optimizing Your Computer for Audio - Windows 10](https://support.presonus.com/hc/en-us/articles/360025279231-Optimizing-Your-Computer-for-Audio-Windows-10) guide;
- Focusrite's [Optimising Windows for Audio](https://support.focusrite.com/hc/en-gb/articles/207355205-Optimising-Windows-for-Audio) pages;
- Audinate's [How can I tune a Windows PC for best audio performance?](https://www.getdante.com/support/faq/how-can-i-tune-a-windows-pc-for-best-audio-performance) FAQ;

By Pete Brown (Microsoft dev):
- [Unofficial Windows 10 Audio Workstation build and tweak guide – Part 1](https://devblogs.microsoft.com/windows-music-dev/unofficial-windows-10-audio-workstation-build-and-tweak-guide-part-1/#comments);
- [Unofficial Windows 10 Audio Workstation build and tweak guide – Part 2](https://devblogs.microsoft.com/windows-music-dev/unofficial-windows-10-audio-workstation-build-and-tweak-guide-part-2/);

Other:
- [How to Optimize Windows 10 for Music Production](https://musicproductionnerds.com/how-to-optimize-windows-10-for-music-production) by MusicProductionNerds.com;
- [20 ways to optimize your Windows 10 PC for music production](https://bandzoogle.com/blog/20-ways-to-optimize-your-windows-10-pc-for-music-production) by Bandzoogle Blog;
- [AudiophileOptimizer Setup Guide](https://www.highend-audiopc.com/PDF/audiophile-optimizer-setup-guide.pdf) (PDF) by Highend-AudioPC

Hope that inspires !

**Comment by mewostick** [comment]
Hi, SamuraiOS was a Windows ISO modified with NTLite I once made for fun and never bothered to update nor publish it online. I have archived the files for it in that repository so I don't easily lose those them in case they ever come useful again.

WinScripts is just a simple script meant to run other popular PowerShell scripts and make very simple registry changes - it was to save me time by not having to search for each scripts' URL to run in PS every time I had a fresh copy of Windows.

About multimedia production, I could attempt to make an AME Wizard playbook for that but I can't reliably test if there are going to be latency and/or other issues with it since the only multimedia I ever produced are simple videos.
However, I've yet to see a playbook for production so the idea is interesting! I'll take a look at other playbooks and the documentation to learn about how it works.

Thank you for reaching out!

**Comment by MarcoRavich** [comment]
> Hi, SamuraiOS was a Windows ISO modified with NTLite I once made for fun and never bothered to update nor publish it online. I have archived the files for it in that repository so I don't easily lose those them in case they ever come useful again.
> 
> WinScripts is just a simple script meant to run other popular PowerShell scripts and make very simple registry changes - it was to save me time by not having to search for each scripts' URL to run in PS every time I had a fresh copy of Windows.
> 
>
Thanks for the explainations !


> About multimedia production, I could attempt to make an AME Wizard playbook for that but I can't reliably test if there are going to be latency and/or other issues with it since the only multimedia I ever produced are simple videos.
>
Well, I do audio/video editing (with [Vegas Pro 22](https://www.vegascreativesoftware.com/)) in my Windows-based PCs, so I can also test your Playbook(s) for you if you need.
Of course we need to establish which to perform ([Cinebench](https://www.maxon.net/it/cinebench) ? [Phoronix](https://www.phoronix-test-suite.com/) ?) first.

I do also believe that a collaboration with other devs such as @Kerry-Randolph ([performance-pro](https://github.com/Kerry-Randolph/performance-pro)) and/or @rcrath ([bidoptimize](https://github.com/rcrath/bidoptimize)) may help.

> However, I've yet to see a playbook for production so the idea is interesting! I'll take a look at other playbooks and the documentation to learn about how it works.
>
Seems pretty easy, start here: https://docs.ameliorated.io/using-wizard.html
 
> Thank you for reaching out!
>
Thanks for your reply.
Let me know if how I can help you.

Cheers

**Comment by MarcoRavich** [comment]
Funny (but interesting, IMHO) ChatGPT Playbook build: https://chatgpt.com/share/11779cd4-d217-49d9-8a00-3ad72c1ecc6b

**Comment by mewostick** [comment]
> Well, I do audio/video editing (using [Vegas Pro 22](https://www.vegascreativesoftware.com/)) in my Windows-based PCs for [this YT channel](https://forart.it/livinlive), so I can also test your Playbook(s) for you if you need.

Your help would prove useful here.

> Of course we need to establish which to perform ([Cinebench](https://www.maxon.net/it/cinebench) ? [Phoronix](https://www.phoronix-test-suite.com/) ?) first.

I don't really know what are the differences between those two. I've only seen tech youtubers using Cinebench so far.

> I do also believe that some kind of collaboration with other devs such as @Kerry-Randolph ([performance-pro](https://github.com/Kerry-Randolph/performance-pro)), @rcrath ([bidoptimize](https://github.com/rcrath/bidoptimize)), @jonathansandman ([optimise-for-audio-win](https://github.com/jonathansandman/optimise-for-audio-win)) or @helgoboss ([switch-performance-mode](https://github.com/helgoboss/switch-performance-mode)) could help.

Yes, it would greatly help in optimising the OS.

> Seems pretty easy, start here: https://docs.ameliorated.io/using-wizard.html

I did take a look, made a simple playbook that removes some APPX apps and does a couple of registry changes in a minute without me doing anything. Pretty cool :D

> Funny (but interesting, IMHO) ChatGPT Playbook build: https://chatgpt.com/share/11779cd4-d217-49d9-8a00-3ad72c1ecc6b

It seems to have got the format of the playbooks wrong but has useful tweaks ready for me to put into the playbook.

By the way, do you think Windows 10 22H2 would be the best choice here? Or should I try to tweak Windows 11?

**Comment by mewostick** [comment]
> Well, consider me "hired" then.

What's your preferred private way of contact? 

> ...then I do believe that a mixup of benchmarking tools could be the right choice: I'll digg deep and let you know.

Sure!

> Yes, it's quite simple, but - of course - if you check AtlasOS or ReviOS they're quite more complex, involving powershell an so on...

I'm likely going to rely on some CMD/PowerShell scripts later on as well to do some stuff not possible with AME itself.

> but, with due human supervision, it can help/inspire and sometime facilitate the achievement of the goal...

I've been using it myself and it's really great help once one starts using their head.

> That's why - to me - a Playbook that can fit both (W11 and W10) would be the best.

Knowing Windows, most if not all optimisations should work fine. I don't think it will be much of a challenge to make the playbook work on 10 and 11.

**Comment by MarcoRavich** [comment]
> What's your preferred private way of contact?
> 
Release everything I worked on as GPL and/or CC By-NC-SA for sure.

> Sure!
> 
I'll investigate further, I'll bit busy since I have local shows (that I must attend as audio/video tech) scheduled for all the September's weekends...

> I'm likely going to rely on some CMD/PowerShell scripts later on as well to do some stuff not possible with AME itself.
> 
About this: I've cited you in [Vitality discussion](https://github.com/vojtikczhraje/Vitality/issues/1), where Voj (the author) seems intent on evolving his into a standalone executable.

> I've been using it myself and it's really great help once one starts using their head.
> 
Yup, I'm using it in my daily job too. But always supervised.

> Knowing Windows, most if not all optimisations should work fine. I don't think it will be much of a challenge to make the playbook work on 10 and 11.
>
Most likely yes. Anyway please take in consideration that my tests will be mainly on Windows 11 (I can also arrange a Win10 PC too, but not soon).

Let's stay in touch.

**Comment by mewostick** [comment]
> I'll investigate further, I'll bit busy since I have local shows (that I must attend as audio/video tech) scheduled for all the September's weekends...

> ...not only, I'm already "hired" (as a volunteer, of course) for a machine learning experiment about indipendent artists' Signature Guitar Tones.

Sure, good luck!

> About this: I've cited you in https://github.com/vojtikczhraje/Vitality/issues/1, where Voj (the author) seems intent on evolving his into a standalone executable.

It is an interesting project indeed, what are you suggesting?

> Most likely yes. Anyway please take in consideration that my tests will be mainly on Windows 11 (I can also arrange a Win10 PC too, but not soon).

Windows 11 will be fine. I'm primarily testing in VMware to see if everything works like it is supposed to - currently on Windows 10 but once I'm done with applying all the tweaks to the playbook I'll test 11.
If it turns out to work fine in my VM I'll push the files to the [Creosynth repository](https://github.com/mewostick/Creosynth) for anyone to test.

> Let's stay in touch.

I'll let you know when it's ready to test. Cheers!

**Comment by MarcoRavich** [comment]
Hi there,
I digged a bit about latencies optimization - that, as some of the above guides clarify, matters in audio/video production world too - in my (little) spare time and many recommends to follow this non-sponsored YT channel about: [Khorvie Tech](https://www.youtube.com/@khorvietech/videos) ([Guide for Amit's Timer Resolution video](https://www.youtube.com/watch?v=AcCFZ8hhXi8) with resources).

Then I've also searched GH and "some" interesting resources popped out (note: using this post as a notebloc):
- @LuSlower's [ZwTimerResolution](https://github.com/LuSlower/ZwTimerResolution#readme);
- @TorniX0's [OpenTimerResolution](https://github.com/TorniX0/OpenTimerResolution#readme);
- @m-k-dev's [HiResTimersTest](https://github.com/m-k-dev/HiResTimersTest);
- @zCrye's [SnakesTimerResFix](https://github.com/zCrye/SnakesTimerResFix#readme);
- @qzxtu's [ResTimer](https://github.com/qzxtu/ResTimer#readme);
- @llBALAll's [NtSetTimerResolution](https://github.com/llBALAll/NtSetTimerResolution);
- @Aetopia's [TimerResolution](https://github.com/Aetopia/TimerResolution#readme);
- @abort's [W32ResTimer](https://github.com/abort/W32ResTimer#readme);
- @Earthbadger's [TimerResolution](https://github.com/Earthbadger/TimerResolution#readme);
- @valleyofdoom's [TimerResolution](https://github.com/valleyofdoom/TimerResolution#readme);
- @ninetz's [Fix-Windows-Timer-Resolution](https://github.com/ninetz/Fix-Windows-Timer-Resolution#readme);
- @JarateKing's [ForceTimerResolution](https://github.com/JarateKing/ForceTimerResolution#readme);
- @GiordanoSconti's [NtSetTimerResolution](https://github.com/GiordanoSconti/NtSetTimerResolution#readme);
- @how0723's [HighResolutionTimer](https://github.com/how0723/HighResolutionTimer#readme);
- @snowyoneill's [HighResTimerWithErrorChecking](https://github.com/snowyoneill/HighResTimerWithErrorChecking);

...hope someone is interested in collaborate to determine how optimeze Windows' TimerResolution for multimedia content creation.

**Comment by MarcoRavich** [comment]
Forgot to mention [The ONLY Windows PC OPTIMIZATION Guide You Will EVER Need In 2024 video](https://www.youtube.com/watch?v=iBiNfa32AnE) (with resources) by [Khorvie Tech](https://www.youtube.com/@khorvietech) too.

It may inspire.

**Comment by zCrye** [comment]
Hello, as you have already noticed, amits TimerResolution only works in Windows 2020 and Windows 11 22h2+. The driver I wrote back then should work in Windows 7, Windows 10 and Windows 11 without any problems. (The driver sets the system-wide TimerResolution (and Sleep) to 1ms.However, I stopped at that time because a certificate is needed and I couldn't find anyone who could have signed the driver free of charge. (I also contacted inquiries to companies that sell certificates at that time, but without success.)I tried it possible at the time, drivers, programs, services, dll, custom os, that can change the TimerResolution, received access violations or didn't work (Sleep (1) = 15+ms.The driver (SnakesTimerResFix) works in test mode or via kdmapper).-------- Ursprüngliche Nachricht --------Von: Marco Ravich ***@***.***>Datum: Fr., 30. Aug. 2024, 08:33An: mewostick/WinScripts ***@***.***>Cc: juﮎtin ***@***.***>, Mention ***@***.***>Betreff: Re: [mewostick/WinScripts] [SUGGESTION] AME Playbook (Issue #1)
Hi there,
I digged a bit about latencies optimization - that, as some of the above guides clarify, matters in audio/video production world too - in my (little) spare time and many recommends to follow this non-sponsored YT channel about: Khorvie Tech (Guide for Amit's Timer Resolution video with resources).
Then I've also searched GH and "some" interesting resources popped out (note: using this post as a notebloc):
@LuSlower's ***@***.***'s ***@***.***'s ***@***.***'s ***@***.***'s ***@***.***'s ***@***.***'s ***@***.***'s ***@***.***'s ***@***.***'s ***@***.***'s ***@***.***'s ***@***.***'s ***@***.***'s ***@***.***'s HighResTimerWithErrorChecking;
...hope someone is interested in collaborate to determine how optimeze Windows' TimerResolution for multimedia content creation.

**Comment by zCrye** [comment]
GlobalTimerResolutionRequests is the key to success in Windows 11. However, it was removed in Windows 10 and added back in Windows 11. If you're specifically interested in Windows 10, there are only two ways I could figure out. However, my driver, SnakesTimerResFix (kdmapper/test mode) or windbg, only works with second system (VMware, and test mode. If you're interested in Windows 11, GlobalTimerResolutionRequests is the only way to get Sleep as close to TimerResolution as possible. (Should work via ZwQueryTimerResolution, NtSetTimerResoution, QueryPerformanceCounter <- (not sure if it was called that.) and a few others.(I can provide you with test attempts, codes, information if you have any questions.)~zCryeVon meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Marco Ravich ***@***.***>Datum: Fr., 30. Aug. 2024, 09:01An: mewostick/WinScripts ***@***.***>Cc: juﮎtin ***@***.***>, Mention ***@***.***>Betreff: Re: [mewostick/WinScripts] [SUGGESTION] AME Playbook (Issue #1)
Forgot to mention The ONLY Windows PC OPTIMIZATION Guide You Will EVER Need In 2024 video (with resources) by Khorvie Tech too.
It may inspire.

**Comment by zCrye** [comment]
I had the same plan, to program something with which you can get the maximum performance and the lowest latency out of Windows and that for everyone and in addition to what these settings e.g. make. (1 tool for all, Clean up, tweaks, also things like latency for audio. ) 

![Screenshot_20240830_095933_com discord](https://github.com/user-attachments/assets/ab2710a4-e504-46a0-b39d-bf0cbf454aa6)


![Screenshot_20240830_095357_com discord](https://github.com/user-attachments/assets/23bb1be9-f3bb-4b1f-862c-c4ef33bc39b7)

**Comment by mewostick** [comment]
> GlobalTimerResolutionRequests is the key to success in Windows 11. However, it was removed in Windows 10 and added back in Windows 11. If you're specifically interested in Windows 10, there are only two ways I could figure out. However, my driver, SnakesTimerResFix (kdmapper/test mode) or windbg, only works with second system (VMware, and test mode. If you're interested in Windows 11, GlobalTimerResolutionRequests is the only way to get Sleep as close to TimerResolution as possible. (Should work via ZwQueryTimerResolution, NtSetTimerResoution, QueryPerformanceCounter <- (not sure if it was called that.) and a few others.(I can provide you with test attempts, codes, information if you have any questions.)

Hi, I'm developing for both Windows 10 (22H2) and Windows 11 (23H2). Thanks for the explanation!

Seeing as there is no easy way to set 'GlobalTimerResolutionRequests' in Windows 10 and one would need to install a driver with test mode (which can prove insecure), I won't most likely be including a fix for Timer Resolution in Windows 10 out of the box.

For Windows 11 I've searched a bit and found this .reg file. Is it as simple as setting that registry entry to '1' or does it go deeper?
![Screenshot from 2024-08-30 10-02-29](https://github.com/user-attachments/assets/62a3c4f2-3862-4e22-b9ba-de79cc6dc498)

**Comment by zCrye** [comment]
Drivers seem to be the only option in Windows 10+, without a certificate it won't work. Kdmapper would be an alternative for this, but I advise against it. 

GlobalTimerResolutionRequests works in Windows 10 2020 and in Windows 11 (as far as I know still in older Windows versions). However, there is only GlobalTimerResolutionRequests 1 to enable it and 0 / delete key to disable it.

With the help of GlobalTimerResolutionRequests, it is possible to change the sleep (1), which is normally 15ms, to the maximum. (Assuming we set the TimerResolution without GlobalTimerResolutionRequests 1 to 2ms, we get the following values:"TimerResolution 2ms Sleep(1) 15ms+." If we use the whole thing now with GlobalTimerResolutionRequests 1 we would get the following: "TimerResolution 2ms Sleep(1) 2ms+") 

I haven't stopped, I rarely continue to work on it.

**Comment by MarcoRavich** [comment]
...menwhile the "fun" chat did some steps ahead: https://chatgpt.com/share/11779cd4-d217-49d9-8a00-3ad72c1ecc6b

**Comment by mewostick** [comment]
Hi, I pushed playbook files for testing into the [Creosynth](https://github.com/mewostick/Creosynth/tree/main/playbook) repo. 

Report any breakages on the [issues page](https://github.com/mewostick/Creosynth/issues).

I recommend we continue this discussion at [Creosynth discussions](https://github.com/mewostick/Creosynth/discussions/1)!
